### ISSUE TITLE
Feature request: csv.gz by data.table

### ISSUE THREAD

**Issue by statquant** [gesistsa/rio#253]
Hello, I noticed `csv.gz` is not loaded via data.table while data.table now natively reads gzipped files. Is there a reason for it ?
Also, can I suggest adding support for [qs](https://github.com/traversc/qs), qs provides fast serialization for R objects, and is even faster than fst. The huge plus is that it works for ALL types, so it should really replace rds as it does the same thing but much better.
Regards

**Comment by leeper** [comment]
Thanks. I'll investigate that. Historically, data.table did not support that AFAIK and I'm pretty conservative on adding new features until they're stable in underlying packages.

qs is mentioned as a recognized but unsupported import/export here: https://github.com/leeper/rio/blob/master/R/extensions.R#L41, https://github.com/leeper/rio/blob/master/R/extensions.R#L68. Might promote it to a suggested feature in the future.

**Comment by statquant** [comment]
With regards to csv.gz it is released in cran for some time now. I am a bit of a groupie of you can trust data.table to have high quality standards. They also support csvy format. You might even succeed in removing a few dependencies (which I see as a good thing myself)

**Comment by schochastics** [comment]
will be fixed with #343
