### ISSUE TITLE
Feature add qs support 

### ISSUE THREAD

**Issue by statquant** [gesistsa/rio#275]
Hello,
just a quick note that I think qs should be added to the supported formats. qs claims to be as fast as fst for read/write data.frames but its major advantage is that it supports all object types (typjcally lists). In my opinion it makes it the format of choice for binary save/read anything.
Thanks and regards

**Comment by leeper** [comment]
This is mentioned as a suggested format. I think I'll leave it as that for now.

**Comment by chainsawriot** [comment]
#218

**Comment by chainsawriot** [comment]
As well as #253

**Comment by chainsawriot** [comment]
fixed by #341
