### ISSUE TITLE
Suggestion: Minor change for a more helpful error code

### ISSUE THREAD

**Issue by MCodrescu** [gesistsa/rio#301]
Please specify whether your issue is about:

 - [ ] a possible bug
 - [ ] a question about package functionality
 - [X] a suggested code or documentation change, improvement to the code, or feature request

If you are reporting (1) a bug or (2) a question about code, please supply:

 - [a fully reproducible example](http://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example) using a publicly available dataset (or provide your data)
 - if an error is occurring, include the output of `traceback()` run immediately after the error occurs
 - the output of `sessionInfo()`

Put your code here:

```R
data <- data.frame(
  x = sample(1:10, 10000, replace = TRUE),
  y = sample(1:10, 10000, replace = TRUE)
)

result <- rio::import(data)
#> Error in if (grepl("^http.*://", file)) {: the condition has length > 1
```
When the value of the file parameter of the import function is a data frame by accident instead of a file path it gives an unhelpful error message.  I think this could be solved by switching the order of the following two if statements in the import function.
```R
if (grepl("^http.*://", file)) {
        file <- remote_to_local(file, format = format)
    }
if ((file != "clipboard") && !file.exists(file)) {
    stop("No such file")
}
```

**Comment by chainsawriot** [comment]
Similar things for

- [ ] `import_list`
- [ ] `export`
- [ ] `export_list`
