### ISSUE TITLE
Switch from `openxlsx` to `writexl`

### ISSUE THREAD

**Issue by chainsawriot** [gesistsa/rio#310]
For the purpose of this package (exporting rectangular data, no formatting), `writexl` is probably enough.

**Comment by chainsawriot** [comment]
Maybe also a good idea to switch off `import("abc.xlsx", readxl = FALSE)`

https://github.com/chainsawriot/rio/blob/5328dffa5aaf3acdcaa9d446725b574714b0adab/R/import.R#L24

**Comment by briatte** [comment]
I came here to suggest the same thing.

See also #96 

See also `openxlsx2`, which does the same thing as `openxlsx` and `writexl`, but with many more dependencies than the latter:

https://janmarvin.github.io/openxlsx2/index.html
