### ISSUE TITLE
FR: Add a pkg website

### ISSUE THREAD

**Issue by olivroy** [gesistsa/rio#316]
i.e. a pkgdown website.

usethis::use_pkgdown_github_pages()

https://usethis.r-lib.org/reference/use_pkgdown.html

**Comment by chainsawriot** [comment]
There was. And I categorically removed it.

**Comment by olivroy** [comment]
May I ask the reason why?

**Comment by chainsawriot** [comment]
#317 

If it got accepted by rOpenSci, they will handle this.
