### ISSUE TITLE
checking of `data.table` in ... vs `setclass`

### ISSUE THREAD

**Issue by chainsawriot** [gesistsa/rio#336]
https://github.com/gesistsa/rio/blob/067a0ae805fdd96816fe9103af9f1843df3584a2/R/import.R#L141-L158

https://github.com/gesistsa/rio/blob/067a0ae805fdd96816fe9103af9f1843df3584a2/R/import_list.R#L128-L147

It's kind of out of context to do this inside `import()` and `import_list()`

**Comment by chainsawriot** [comment]
As a background, `data.table` is actually a parameter of `data.table:fread()` and default to `TRUE` (at least when one doesn't set the options). BTW, `readODS::read_ods()` v2.0 now has `as_tibble` and default to `TRUE`. If `data.table` is respected, so should `as_tibble`.

The checking in `import()` and `import_list()` here basically is making `data.table` a de facto undocumented feature even for the importing function not using `data.table::fread()`, see the ods case (which use `readODS::read_ods()`, and the warning is confusing)

``` r
x1 <- tempfile(fileext = ".csv")
rio::export(mtcars, file = x1)
y1 <- rio::import(x1, data.table = TRUE)
class(y1)
#> [1] "data.table" "data.frame"

x2 <- tempfile(fileext = ".ods")
rio::export(mtcars, file = x2)
y2 <- rio::import(x2, data.table = TRUE)
#> Warning in .import.rio_ods(file = file, ...): The following arguments were ignored for read_ods:
#> data.table
class(y2)
#> [1] "data.table" "data.frame"
```

<sup>Created on 2023-09-04 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

What I wanted to argue here is that it is almost impossible to chase and override all of them. How about we just let `setclass` to always have the last say.

**Comment by chainsawriot** [comment]
Another option is to ditch `setclass` altogether and make `data.table` and `tibble` formal arguments of `import()` and `import_form()`. If both `FALSE`, get a vanilla `data.frame`. Probably can't be both `TRUE`.

**Comment by schochastics** [comment]
Here is my opinion after looking at the code (but without knowing how people tend to use the function, and not knowing much of the history of rio yet):
The return type should be explicitly specified with the `setclass` parameter which should default to `data.frame` (could also be a tibble) and it should not be encouraged to change the class with special parameters in `...`, i.e. setclass is authoritative. Not sure how much this would break for people, but I think it would be good to have a parameter dedicated to the returned class.

**Comment by chainsawriot** [comment]
`setclass = getOption("rio.import.class", "data.frame")` is probably a better default. Missing as default to export "data.frame" is not expressive. (`NULL` to bypass `setclass` is not documented too)

So that one can set the default class: `options(rio.import.class = "data.table")` or `option(rio.import.class = "tibble")`. If one wants to be explicit: `setclass = "tibble"`.

And ditch the checking of `data.table` (or `as_tibble` or whatever) in `...` Say it explicitly in the doc that `setclass` always has the final say. Demo it in the examples.

**Comment by schochastics** [comment]
yes `getOption` is even better. I definitely like this approach

**Comment by chainsawriot** [comment]
43d544ba0044bf27c0be414f18b94b34f143f8c5

https://github.com/gesistsa/rio/blob/81c04236dab444aaea9b9ca953f48ccc33ba4d88/R/import.R#L134-L136

This check is weird (rds, rdata, and json to skip `setclass` en masse). If the output is data.frame, I think it should still go through `setclass`.

What should be checked is `x` instead.

**Comment by chainsawriot** [comment]
#183

`rdata`, `rds`, `json`, `gs`, `r`, `dump`, `yaml` can be arbitrary R objects.

**Comment by schochastics** [comment]
> [43d544b](https://github.com/gesistsa/rio/commit/43d544ba0044bf27c0be414f18b94b34f143f8c5)
> 
> https://github.com/gesistsa/rio/blob/81c04236dab444aaea9b9ca953f48ccc33ba4d88/R/import.R#L134-L136
> 
> This check is weird (rds, rdata, and json to skip `setclass` en masse). If the output is data.frame, I think it should still go through `setclass`.
> 
> What should be checked is `x` instead.

Another plays where I forgot `qs`?
