### ISSUE TITLE
Use `R.utils`

### ISSUE THREAD

**Issue by chainsawriot** [gesistsa/rio#363]
As `R.utils` is introduced in #362 

- [x] `R.utils::isURL`

https://github.com/gesistsa/rio/blob/0cb72f172b40cbb32a4484a1a738b56773fe431c/R/import.R#L105

- [ ] `R.utils::mkdirs`

https://github.com/gesistsa/rio/blob/0cb72f172b40cbb32a4484a1a738b56773fe431c/R/export.R#L105

- [x] `R.utils::doCall` rather than `arg_reconcile`?

Anymore?

**Comment by chainsawriot** [comment]
- [ ] `R.utils::isPackageInstalled`

https://github.com/gesistsa/rio/blob/0cb72f172b40cbb32a4484a1a738b56773fe431c/R/suggestions.R#L21-L32

**Comment by chainsawriot** [comment]
Research

- [ ] Can #319 be fixed by R.utils compression functions?

**Comment by schochastics** [comment]
> Research
> 
>     * [ ]  Can [gp issues #319](https://github.com/gesistsa/rio/issues/319) be fixed by R.utils compression functions?

I could so far not make `compressFile` compress to a valid zip archive
