### ISSUE TITLE
The `trust` argument of `import()` should be explicit for serialization formats as of rio 1.0.3.

### ISSUE THREAD

**Issue by atoosy** [gesistsa/rio#450]
The `trust` argument of `import()` should be explicit for serialization formats as of rio 1.0.3.
ℹ Missing `trust` will be set to FALSE by default for RDS in 2.0.0.
ℹ The deprecated feature was likely used in the rio package.
  Please report the issue at <https://github.com/gesistsa/rio/issues>.

**Comment by chainsawriot** [comment]
#432
