### ISSUE TITLE
Problems installing parts of rio

### ISSUE THREAD

**Issue by SaraT19-jpg** [gesistsa/rio#452]
The `trust` argument of `import()` should be explicit for serialization formats as of rio 1.0.3.
ℹ Missing `trust` will be set to FALSE by default for RDS in 2.0.0.
ℹ The deprecated feature was likely used in the rio package.

When I install rio I get the message 'The following rio suggested packages are not installed: ‘nanoparquet’, ‘hexView’, ‘fst’, ‘arrow’, ‘pzfx’, ‘rmatio’, ‘readODS’, ‘qs’
Use 'install_formats()' to install them'

When I try install_formats I get a failed message that the object is not found.

**Comment by chainsawriot** [comment]
@SaraT19-jpg I think you are reporting two things here (or you would like to report that both are related?)

For the first item, please see #450 or the FAQ.

For the second item, you don't necessarily need to install all suggested packages; only if you need to use those additional formats. See https://github.com/gesistsa/rio?tab=readme-ov-file#supported-file-formats

However, if you want to install those suggested packages, please provide the error message (and your OS).
