### ISSUE TITLE
import sas7bdat extension deprecated in haven package

### ISSUE THREAD

**Issue by yannjay** [gesistsa/rio#459]
> library(rio)
> sas_file <- tempfile(fileext = ".sas7bdat")
> export(mtcars, sas_file)
Warning message:
`write_sas()` was deprecated in haven 2.5.2.
ℹ Please use `write_xpt()` instead.
ℹ The deprecated feature was likely used in the rio
  package.
  Please report the issue at
  <https://github.com/gesistsa/rio/issues>.
This warning is displayed once every 8 hours.
Call `lifecycle::last_lifecycle_warnings()` to see
where this warning was generated.

**Comment by chainsawriot** [comment]
@yannjay The deprecation message has stated what you should do.
